# Generated by Django 5.0.7 on 2024-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="created_at",
        ),
        migrations.AddField(
            model_name="author",
            name="see_also",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=100),
        ),
    ]
